## Importing Necessary Libraries

In [1]:
import numpy as ny
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import os

In [5]:
df = pd.read_csv(r"C:\Users\ADMIN\Desktop\ITDSIU21099_HoangVanManh\Fashion-Marketing-Automation-Solutions\data\processed\posts.csv")
df.head()

,post_id,timestamp,ownerUsername,type,caption,hashtags,likesCount,commentsCount,image
0,1,2023-06-02 16:34:43+00:00,maryleest,Sidecar,Cannes 2023 with @kilianparis 🤍 #KilianCannes ...,KilianCannes,32070,142,https://scontent-ord5-1.cdninstagram.com/v/t51...
1,2,2023-01-01 07:49:16+00:00,tinaabeysekara,Sidecar,"As the clock struck midnight to ring in 2022, ...",NaN,6565,86,https://instagram.fyei4-1.fna.fbcdn.net/v/t51....
2,3,2023-05-29 18:57:51+00:00,maryleest,Sidecar,The famous stairs 🤎 Photo @gustave_durin Dre...,NaN,28936,123,https://instagram.fpeg1-2.fna.fbcdn.net/v/t51....
3,4,2023-03-07 19:30:42+00:00,stephaniebroek,Sidecar,I visualized this moment so many times before....,CHANELFallWinter,4764,215,https://scontent-lhr8-1.cdninstagram.com/v/t51...
4,5,2023-05-23 21:11:12+00:00,maryleest,Sidecar,Got to witness such historical moment in cinem...,CannesFilmFestival,13379,123,https://instagram.fprg5-1.fna.fbcdn.net/v/t51....

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 827 entries, 0 to 826
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   post_id        827 non-null    int64
 1   timestamp      827 non-null    object
 2   ownerUsername  827 non-null    object
 3   type           827 non-null    object
 4   caption        820 non-null    object
 5   hashtags       474 non-null    object
 6   likesCount     827 non-null    int64
 7   commentsCount  827 non-null    int64
 8   image          827 non-null    object
dtypes: int64(3), object(6)
memory usage: 58.3+ KB

In [7]:
df.describe()

         post_id    likesCount  commentsCount
count  827.00000  8.270000e+02     827.000000
mean   414.00000  5.256894e+05    1206.575574
std    238.87863  1.770391e+06    5375.458118
min      1.00000  9.000000e+00       0.000000
25%    207.50000  8.735000e+02      10.000000
50%    414.00000  4.244000e+03      46.000000
75%    620.50000  1.224755e+05     230.500000
max    827.00000  1.382552e+07   83042.000000